### PR TITLE
Event fired when option clicked

### PR DESCRIPTION
**Pull request by halufa**
In my project I need to know when the user clicks one of the search result options.

### CODE REVIEW

**Comment by bung87** [comment]
you can provider `resultItemClickCallback` option  by write a callback function like https://github.com/bung87/leaflet-searchbox/blob/master/src/index.js#L30

**Comment by halufa** [comment]
I made a Pull Request with a change to the resultItemClickCallback function, adding the new event I need. I think it would be a good improvement on your package.

If you don't want to merge that piece of code, can you explain me how can I "provide" my own resultItemClickCallback function ?

Thanks.

**Comment by bung87** [comment]
see https://github.com/bung87/leaflet-searchbox#options

the SearchBox constructor accept an object as options . available options list above, it inherit from leaflet base class, so just like leaflet basic classes that constructor always accept an options.

and see example
https://github.com/bung87/leaflet-searchbox#code-example

map listen on 'geosearch/showlocation' event. 

this lib doest meat to have a default `resultItemClickCallback` , it's just demonstrate to developer how to write a `resultItemClickCallback` has option, the  default `resultItemClickCallback` is very simple, can't be used as production, fire multiple events on item click is duplicated.

you just need write a function like `resultItemClickCallback` 
```
var options = {resultItemClickCallback:Your_resultItemClickCallback}
new SearchBox(options)
```

**Comment by halufa** [comment]
Thanks man.

I got it to work as I wanted to, although it was not very pretty since there's no acess to SearchBox object instance inside the callback function. I had to make a workaround to use the "this._hideSearchResult();".

It's all good and working, thanks again and best regards.

**Comment by bung87** [comment]
the callback has searchbox context through `this`, you can see it documebted in readme as `context`

**Pull request closed without merging**
